<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.skyblockexp</groupId>
    <artifactId>EzFramework</artifactId>
    <version>0.1.0</version>
    <packaging>pom</packaging>
    <name>EzFramework</name>
    <description>EzFramework multi-module parent POM</description>

    <modules>
        <module>ezframework-query</module>
        <module>ezframework-core</module>
        <module>message-minimessage</module>
        <module>ezframework-cli</module>
        <module>storage-mysql</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        
        <github.owner>ez-plugins</github.owner>
        <github.repository>ezframework</github.repository>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.spigotmc</groupId>
                <artifactId>spigot-api</artifactId>
                <version>1.21.11-R0.1-SNAPSHOT</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <distributionManagement>
        <repository>
            <id>github</id>
            <name>GitHub Packages</name>
            <url>https://maven.pkg.github.com/${github.owner}/${github.repository}</url>
        </repository>
    </distributionManagement>
</project>
